export const ASSUNTOS = [
  "ACESSIBILIDADE",
  "AUSÊNCIA DE AGENTE DE BORDO",
  "COMPORTAMENTO INADEQUADO DO MOTORISTA",
  "CONDIÇÕES DO VEÍCULO",
  "EXCESSO DE PASSAGEIROS",
  "FALTA DE ÔNIBUS",
  "FALTA DE PARADA",
  "HORÁRIOS / ATRASOS",
  "ITINERÁRIO / ROTA",
  "LIMPEZA DO VEÍCULO",
  "OUTROS",
];

export const LINHAS = [
  "85 - EST.S.GABRIEL/CENTRO - VIA FLORESTA",
  "812 - ESTAÇÃO SÃO GABRIEL",
  "815 - ESTAÇÃO SÃO GABRIEL/CONJ. PAULO VI",
  "822 - ESTAÇÃO JOSÉ CÂNDIDO / VILA MARIA",
  "5201 - DONA CLARA/BURITIS",
  "5401 - SÃO LUIZ/DOM CABRAL",
  "9105 - NOVA VISTA/SION",
  "9204 - SANTA EFIGÊNIA/ESTORIL",
  "9208 - TAQUARIL/CONJ. SANTA MARIA",
  "9211 - CAETANO FURQUIM/HAVAI",
  "9214 - CAETANO FURQUIM/HAVAI - VIA ALTO HAVAI",
  "9250 - CAETANO FURQUIM/NOVA CINTRA",
];

export const SLA_DIAS = 7;
export const MIN_DESCRICAO_LENGTH = 20;
export const MAX_DESCRICAO_LENGTH = 1000;
